export {
  RegisterPage,
  GuardMainPage,
  ServiceHistoryPage,
  GuardMyPage,
  GuardReportPage,
  SinittoReviewPage,
  ServiceManualPage,
  SeniorRegisterPage,
  GuideLinePage,
  HelloCallApplyPage,
  SinittoMainPage,
  SinittoMyPage,
  HelloCallListPage,
  HelloCallServicePage,
  HelloCallReportPage,
  CallBackListPage,
  CallBackDetailPage,
  SinittoGuideLinePage,
  SinittoServiceHistoryPage,
  HelloCallDetailPage,
} from './LazyLoading';
