export const RouterPath = {
  ROOT: '/',
  LOGIN: '/login',
  SIGNUP: '/signup',
  REGISTER: '/register',
  GUARD_MYPAGE: `/guard/mypage`,
  GUARD_GUIDELINE: `/guard/guideline`,
  SINITTO_MYPAGE: `/sinitto/mypage`,
  SERVICE_HISTORY: `/service-history`,
  HELLO_CALL_SERVICE: 'service',
  HELLO_CALL_REPORT: 'report',
  HELLO_CALL: `/hello-call`,
  CALL_BACK_LIST: '/call-back',
  CALL_BACK_DETAIL: ':callBackId',
  CALL_BACK_GUID_LINE: ':guideLineId',
  SENIOR_REGISTER: `/senior-register`,
  SINITTO_REVIEW: `/sinitto-review`,
};
