export const RouterPath = {
  root: '/',
  login: '/login',
  register: '/register',
  mypage: `/mypage`,
  serviceHistory: `/service-history`,
  helloCallService: 'service',
  helloCallReport: 'report',
  helloCall: `/hello-call`,
  callBackList: '/call-back',
  callBackDetail: ':callBackId',
  callBackGuidLine: ':guideLineId',
  seniorRegister: `/senior-register`,
  siniddoReview: `/siniddo-review`,
};
