name: ESLint & Build Test

on:
  pull_request:
    branches:
      - Master
      - Develop
      - Weekly
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install NodeJs
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Pnpm package manager
        run: |
          npm install -g pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Lint Code
        run: pnpm lint
      
      - name: Build Test
        run: |
          echo "build를 진행하여 배포시 오류가 발생하는지 확인합니다."
          pnpm run build
