name: ESLint & Build Test

on:
  pull_request:
    branches:
      - Master
      - Develop
      - Weekly
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install NodeJs & Pnpm package manager
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Lint Code
        run: pnpm lint
      
      - name: Build Test
        run: pnpm run build
